### ISSUE TITLE
第二种DTU的评估方式

### ISSUE THREAD

**Issue by KyrieLiu52** [MiZhenxing/GBi-Net#1]
您好
您的论文中提到对DTU数据集使用了两种评价指标，第二种是直接评估深度图预测的准确性。
请问这部分是您自己提出的一种评价方法，还是类似第一种基于距离的评价指标，由其他方法（如DTU）提供的评估方式。
谢谢！

**Comment by MiZhenxing** [comment]
Hi, the second evaluation metric directly subtracts the predicted depth maps with the gt depth maps and gets the absolute error. Then we set a threshold and compute the percentage of pixels whose error is below the threshold.
You could reference the code in [MVSNet-pytorch](https://github.com/xy-guo/MVSNet_pytorch).
https://github.com/xy-guo/MVSNet_pytorch/blob/e0f2ae3d7cb2dd13807b775f2075682eaa7f1521/utils.py#L139-L146

**Comment by KyrieLiu52** [comment]
非常感谢您的回复
