### ISSUE TITLE
About the method of upsampling

### ISSUE THREAD

**Issue by qtz980805** [MiZhenxing/GBi-Net#2]
Thanks for your significiant work. I would like to ask the method of upsampling the depth hypotheses. Is it the nearest interpolation or the bilinear interpolation? I think both of them would influence the accuarcy, especially in edge regions. 
Look forward for your reply!

**Comment by MiZhenxing** [comment]
Hi, among the different scales, we directly upsample the depth map of the previous scale and then recompute which bin each depth is in. When upsampling the depth maps, we use bilinear interpolation.

**Comment by qtz980805** [comment]
Thanks a lot for your kind reply.
