### ISSUE TITLE
classification or regression?

### ISSUE THREAD

**Issue by DIVE128** [MiZhenxing/GBi-Net#4]
Thanks for your great work. As for the depth generation, you choose argmax of classification instead of weighed operation of regression. Does it increase the risk to predict a wrong depth range in the early stage? What do you think about the choice of classification and  regression in multi-view stereo.

**Comment by MiZhenxing** [comment]
Great question. Actually, the MVSNet uses regression and RMVSNet uses regression. And some other methods also have different choices. In our paper, we use a binary search pipeline so we naturally use classification. The possible risk of the wrong prediction is handled by ETB. If you want more discussion about the two kinds of methods, I recommend you to read the paper of this code [UniMVSNet](https://github.com/prstrive/UniMVSNet).
