### ISSUE TITLE
About the reason of using Rectified_raw in dtu_yao?

### ISSUE THREAD

**Issue by qtz980805** [MiZhenxing/GBi-Net#8]
Thanks for releasing the code!
I would like to ask about the reason of using Rectified_raw in dtu_yao?
As you coded in dtu yao, the original img is first read from the "Rectified_raw" folder, and then croped. This process can be regarded as the preprocessing of MVSNet, which delivers us a "Rectified" folder. So any difference between the above two process.
And can I directly use the  "Rectified" folder from MVSNet. (Forgive me my laziness that I don't want to download the 123GB Rectified_raw hhh)
Look forward for your reply！

**Comment by MiZhenxing** [comment]
Hi, there is an optional random cropping data augmentation in our method, see Paper Section 4.2 and Table 1. We need to crop the high-resolution part from the raw image. If you don't want to use this augmentation, it is OK to just use the "Rectified" lower resolution images of MVSNet, maybe need some small code modification.

**Comment by qtz980805** [comment]
Thanks！
